ALTER TABLE workers ADD COLUMN IF NOT EXISTS engine VARCHAR(255);
ALTER TABLE workers ADD COLUMN IF NOT EXISTS num_gpus INT;
ALTER TABLE workers ADD COLUMN IF NOT EXISTS cloud_instance_id VARCHAR(255);
